// import Provider from '@/components/Provider'

export const metadata = {
  title: 'Login Admin',
  description: 'Generated by create next app',
}

export default function AuthLayout({ children }) {
  return <>{children}</>
}