import './globals.css'
import Provider from '@/components/Provider'
import ReduxProvider from '@/redux/ReduxProvider'
import MainLayout from '@/components/layout/MainLayout'


export const metadata = {
  title: 'Neks Ji',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    // <html lang="en" data-theme="light">
    //   <body className={inter.className}>
        <Provider>
          <ReduxProvider>
            <MainLayout>
              {children}
            </MainLayout>
          </ReduxProvider>
        </Provider>
    //   </body>
    // </html>
  )
}
