import './globals.css'
import { Inter } from 'next/font/google'
import Drawer from '@/components/layout/Drawer'
import Navbar from '@/components/layout/Navbar'
import {
  House,
  Whatsapp,
  PersonBadge,
  Key,
  Diagram2,
  People
} from 'react-bootstrap-icons'
import Image from 'next/image'
import ButtonLogout from '@/components/ButtonLogout'
import Link from 'next/link'
import Provider from '@/components/Provider'

const inter = Inter({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Neks Ji',
  description: 'Generated by create next app',
}

const secondaryMenuList = [
  {
    id: 1,
    label: 'Change Password',
    link: '/change-password',
    icon: <Key />
  }
]

const mainMenuList = [
  {
    id: 1,
    label: 'Dashboard',
    link: '/',
    icon: <House />
  },
  {
    id: 2,
    label: 'Blast',
    link: '/blast',
    icon: <Whatsapp />
  },
  {
    id: 3,
    label: 'Accounts',
    link: '/accounts',
    icon: <PersonBadge />
  },
  {
    id: 4,
    label: 'Instances',
    link: '/instances',
    icon: <Diagram2 />
  },
  {
    id: 5,
    label: 'Users',
    link: '/users',
    icon: <People />
  },
]

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="wab">
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
