import Drawer from '@/components/layout/Drawer'
import Navbar from '@/components/layout/Navbar'
import {
  House,
  Whatsapp,
  PersonBadge,
  Key,
  Diagram2,
  People
} from 'react-bootstrap-icons'
import ButtonLogout from '@/components/ButtonLogout'
import Link from 'next/link'
import NavbarTop from '@/components/dashboard/NavbarTop'

export const metadata = {
  title: 'Neks Ji',
  description: 'Generated by create next app',
}

const mainMenuList = [
  {
    id: 1,
    label: 'Dashboard',
    link: '/dashboard',
    icon: <House />
  },
  {
    id: 2,
    label: 'Blast',
    link: '/dashboard/blast',
    icon: <Whatsapp />
  },
  {
    id: 3,
    label: 'Accounts',
    link: '/dashboard/accounts',
    icon: <PersonBadge />
  },
  {
    id: 4,
    label: 'Instances',
    link: '/dashboard/instances',
    icon: <Diagram2 />
  },
  {
    id: 5,
    label: 'Users',
    link: '/dashboard/users',
    icon: <People />
  },
]

const secondaryMenuList = [
  {
    id: 1,
    label: 'Change Password',
    link: '/dashboard/change-password',
    icon: <Key />
  }
]

export default function DashboardLayout({ children }) {
  return (
    <Drawer
      side={
        <Drawer.Side className="flex flex-col font-extralight">
          <Navbar>
            <Link className="btn btn-ghost text-lg" href="/">Next<span className="text-primary">Ji</span></Link>
          </Navbar>
          <div className="flex flex-col justify-between flex-1">
            <Drawer.Menu data={mainMenuList} />
            <Drawer.Menu data={secondaryMenuList}>
              <ButtonLogout />
            </Drawer.Menu>
          </div>
        </Drawer.Side>
      }
      content={
        <Drawer.Content>
          <NavbarTop />
          {children}
        </Drawer.Content>
      }
    />
  )
}
